### ISSUE TITLE
deploying lambda with a different version of aws-sdk

### ISSUE THREAD

**Issue by jodagm** [jaws-framework/JAWS#130] opened 2015-09-19 22:07 UTC
Hi,

My lambdas uses  "aws-sdk": "^2.2.3" (mainly for the new  AWS.DynamoDB.DocumentClient), however according to the docs lambda still runs with sdk version 2.1.35.
When I remove "aws-sdk" from the exclude list in jaws.json, I get this error when testing the lambda by invoking it from API GW console:

 "errorMessage": "Cannot find module '/tmp/dev_-_projectName_-_lambdaName@1442699280155/back/lib/node_modules/aws-sdk/apis/metadata.json'",

I am currently migrating from v0.9.3 to JAWS V1. is this addressed differently on V1?
How do I pack a different aws-sdk version with lambda?

Thanks,
Jonathan

**Comment by DoWhileGeek** [comment] 2015-09-20 05:02
I'm experiencing this as well, its quite a debbie downer.

**Comment by dekz** [comment] 2015-09-20 07:10
I believe [this issue](https://github.com/aws/aws-sdk-js/issues/696) is the cause of aws-sdk being excluded.

Are you able to try removing the browserify builder and attempting to build your lambd?. Everything is moving quite quickly at the moment.

In the jaws.json there is a option for a different builder:

```
  "package": {
      "optimize": {
        "builder": "browserify",
        "minify": true,
        "ignore": [],
        "exclude": [
          "aws-sdk"
        ],
        "includePaths": []
      },
      "excludePatterns": []
    }
```

**Comment by jodagm** [comment] 2015-09-20 10:16
Thanks @dekz it looks like the root cause.

are you suggesting implement another builder? I think the quickest workaround could by keeping browserify but also adding node_modules/aws-sdk to the zip alongside the minified lambda.
I manually edited the zip and uploaded lambda using the console and it worked.
What do you think?

**Comment by binoculars** [comment] 2015-09-20 21:03
I would suggest including the current SDK version in the zipfile or using the legacy library [awslabs/dynamodb-document-js-sdk](/awslabs/dynamodb-document-js-sdk) until AWS updates the AWS SDK for JavaScript to ^2.2.0 for Lambda.

**Comment by jodagm** [comment] 2015-09-20 22:09
Thanks @binoculars, I am trying to figure out if this can be done using one of the existing options in jaws.json (maybe package.includePaths)

**Comment by doapp-ryanp** [comment] 2015-09-21 13:59
Yep @dekz is correct aws-sdk for node [does not support browserify](https://github.com/aws/aws-sdk-js/issues/696).  It is a pretty big bummer.   Maybe some +1's in that thread will help give them more incentive to address the issue in future versions.

In the meantime, I architected JAWS's bundling function to handle this scenario.  What you need to do is leverage the `includePaths` in the `optimize` attr of the `awsm.json`.  Check out the [awsm docs](https://github.com/awsm-org/awsm#configuration).

I will work on adding a test case for this as a reference implementation because I know lots of people will be asking the same question (and the more time elapses, the farther the lambda shipped sdk will get out of date)

**Comment by doapp-ryanp** [comment] 2015-09-21 14:02
Also while this is a bit un-related, I'm guessing people in here care about how AWS manages runtime versions going fwd. Check [this formum post](https://forums.aws.amazon.com/thread.jspa?threadID=180512&tstart=0)

**Comment by jodagm** [comment] 2015-09-21 14:02
This is how I got this working, still optimizing with browserify

created this folder under /back
/back/aws_sdk_deploy/node_modules/aws-sdk
containing the latest aws-sdk

in the module's awsm.json: added aws_sdk_deploy to the includePaths

 "lambda": {
    "envVars": [],
    "deploy": true,
    "package": {
      "optimize": {
        "builder": "browserify",
        "minify": true,
        "ignore": [],
        "exclude": [
          "aws-sdk"
        ],
        "includePaths": [
          "aws_sdk_deploy"
        ]
      },
      "excludePatterns": []
    },
    "cloudFormation": {
      "Description": "",
      "Handler": "aws_modules/myHandler/handler.handler",
      "MemorySize": 1024,
      "Runtime": "nodejs",
      "Timeout": 6
    }
  },

The lambda is now zipped with the correct aws-sdk version and it is also optimized

**Comment by doapp-ryanp** [comment] 2015-09-22 03:50
awesome. thanks for the follow-up. closing.

**Closed by doapp-ryanp** 2015-09-22 03:50 UTC

**Comment by cagataygurturk** [comment] 2015-10-28 21:21
@jodagm then how do you include aws-sdk with this configuration? require('aws-sdk') still points to the default one installed on lambda.

**Comment by reflectivecode** [comment] 2015-12-15 20:00
I wrote a browserify transform that lets you bundle the aws-sdk and optionally lets you specify a subset of services to include. It has been working great with Lambda for us and seemed like something JAWS would benefit from. See [browserify-aws-sdk](https://github.com/asynchrony/browserify-aws-sdk)

**Comment by lynnaloo** [comment] 2017-01-11 02:56
I'm coming across this issue because I want to use the newer version of `aws-sdk` in my `package.json` that contains the Rekognition API. Is there an easier way to resolve this that has come about in the last year?

**Comment by tushar2002jindal** [comment] 2020-12-25 16:20
don't make dynamo a variable 
use
const docClient = new AWS.DynamoDB.DocumentClient();
