### ISSUE TITLE
Slow API gateway endpoints

### ISSUE THREAD

**Issue by joostfarla** [jaws-framework/JAWS#139] opened 2015-09-21 15:45 UTC
When deploying Lambda functions with `jaws dash`, the resulting endpoints are very slow (500ms+). The strange thing is that the exact same Lambda function is performing well (+/- 40ms) when creating the API gateway endpoint manually. API gateway and Lambda are both in regio eu-west-1. I'm aware of the Lambda cold-start issues, but the problem remains when firing multiple subsequent requests.

The difference is visible when comparing these 2 URLs:
```
https://enxk7hdlkl.execute-api.eu-west-1.amazonaws.com/dev/users/list
https://enxk7hdlkl.execute-api.eu-west-1.amazonaws.com/dev/users/test
```

`/list` is generated by `jaws dash`, and `/test` is created manually from the AWS console. Both point to the same Lambda function (no new function is created for the second function).

**Comment by ac360** [comment] 2015-09-21 17:06
@joostfarla Thanks, I'll look into this tonight :)

**Comment by joostfarla** [comment] 2015-09-21 20:18
@ac360 thanx! Did you manage to reproduce this in other regions?

**Comment by joostfarla** [comment] 2015-09-21 21:16
When I query the AWS API for the integration details of both calls, the most important difference I noticed is that the first (slow) request contains a key "credentials" which is absent in the manually created method. Could this be be IAM related?

**Comment by ac360** [comment] 2015-09-22 07:16
@joostfarla This appears to be an API Gateway issue.  The AWS team has been alerted and they are working on it.  The problem is detailed in [this issue](https://github.com/awslabs/aws-apigateway-swagger-importer/issues/41).

I'm going to implement the fix suggested in that issues tomorrow, along with some other API Gateway updates.  Thanks again for spotting this issue.  It looks like AWS didn't even notice it.

**Comment by joostfarla** [comment] 2015-09-22 12:54
Thanx! Great to see such a quick response!

**Comment by ac360** [comment] 2015-09-23 19:36
Still working on this one...  Ran into another AWS bug preventing me from implementing the fix.

https://forums.aws.amazon.com/thread.jspa?threadID=216626&tstart=0

**Comment by ac360** [comment] 2015-09-24 00:20
UGH!  Took all day to fix this one.  But I think I fixed it.  I ran some tests and indeed ~500ms improvements now.  I'm not sure if this will result in a breaking change though.  But it's fixed.  Thanks for pointing this one out @joostfarla.   This is a huge win for JAWS :+1: 

Fixed in 5b5371b0afdd940d16ea96e12d622510955168a0

**Closed by ac360** 2015-09-24 00:20 UTC

**Comment by joostfarla** [comment] 2015-09-24 07:51
This is great! @ac360, many thanx for your hard work!!

**Comment by doriwal** [comment] 2016-12-18 07:55
Hi 

I have problem with api gateway (using Lambda)

when I am doing post request from my android device over network the response is very very slow till i am getting timeout 

but when i am enable wifi on my device the response it within milliseconds 

I cant find an explanation or what to do

**Comment by pmuens** [comment] 2016-12-18 15:54
Hey @doriwal 

Unfortunately that's pretty hard to tell. Seems to be some non-serverless related problem since your application works the way it should if you use a wifi connection.

I'd recommend to raise this question on StackOverflow with some insights into the code and the setup you have.
